#!/bin/sh

# This will disallow pushing with a dirty working tree, which also ensures
# that the pre-push checks run against the same code which is being pushed.
git diff-index --quiet HEAD --
if [[ $? -ne 0 ]]
then
    echo "Fatal: cannot push from a dirty tree, since pre-push checks are then unreliable."
    echo "Try 'git stash' before 'git push'."
    exit 1
fi

exec make check
